config/routes.rb
Canvas::Application.routes.draw do

  match 'grid' => 'public_pages#grid', as: :grid
  match 'support-filter' => 'public_pages#support_filter', as: :support_filter
  match 'radians' => 'public_pages#radians', as: :radians
  match 'geometry-set' => 'public_pages#geometry_set', as: :geometry_set

  root :to => 'public_pages#index'
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/public_pages_controller.rb
class PublicPagesController < ApplicationController
  def index
  end

  def grid
  end

  def support_filter
  end

  def radians
  end

  def geometry_set
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/public_pages_helper.rb
module PublicPagesHelper
end

app/views/layouts/_javascripts.html.haml
= javascript_include_tag 'application'

app/views/layouts/_stylesheets.html.haml
= stylesheet_link_tag 'application', media: "all"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
    = render 'layouts/stylesheets'
    = render 'layouts/javascripts'
    = javascript_include_tag yield(:script)
    = javascript_include_tag yield(:script_02) if defined? :script_02
    = javascript_include_tag yield(:script_03) if defined? :script_03
    = csrf_meta_tags
  %body
    %h1 Fun with Canvas

    = yield

app/views/public_pages/geometry_set.html.haml
# encoding: UTF-8
= provide(:script, 'geometry_set.js')
= provide(:script_02, 'geometry_set_dev.js')

%p
  = link_to 'Back', root_path

.grid
  %canvas#graph_paper{width: 600, height: 400}
.notes
  -#.debug_panel
  %h3 Notes
  %h4 Formulae
  %ul
    %li sin(x) = O/H
    %li O = H * sin(x)
    %li H = sin(x) / O
    %li asin(O/H) = x
    %li radians = degrees * pi/180
    %li degrees = radians * 180/pi
  %h4
    Geometry Set functions
  %ul
    %li
      drawGrid(ctx, canvas);
    %li
      drawAxes(ctx, canvas, x, y);
    %li
      drawXAxis(context, canvas, y);
    %li
      drawYAxis(context, canvas, x);
    %li
      drawPoint(ctx, x, y);
    %li
      drawRect(ctx, x, y, h, w);
    %li
      drawCircle(ctx, x, y, r);
  %h4
    Trigonometry functions
  %ul
    %li
      degrees_to_radians(d);
    %li
      radians_to_degrees(r);

app/views/public_pages/grid.html.haml
= provide(:script, 'grid.js')

%p
  = link_to 'Back', root_path

.grid
  %canvas#grid{width: 600, height: 400}

app/views/public_pages/index.html.haml
%ul
  %li
    = link_to 'Grid', grid_path
  %li
    = link_to 'Test for Canvas support', support_filter_path
  %li
    = link_to 'Radians 01', radians_path
  %li
    = link_to 'Geometry Set development', geometry_set_path

app/views/public_pages/radians.html.haml
= provide(:script, 'radians.js')

%p
  = link_to 'Back', root_path

.grid
  %canvas#radians{width: 600, height: 400}
.notes
  %h3 Notes
  %p
    A Radian: The angle made by wrapping the radius of a circle around it's circumference.
  %ul
    %li
      %h4 Positions around the circle
      %ul
        %li
          3 O'Clock: 0 * Math.PI/4

app/views/public_pages/support_filter.html.haml
%p
  = link_to 'Back', root_path
%p
  %code
    %pre
      = preserve do
        :escaped
          if(canvas.getContext){
            // do drawing
          }else{
            alert('Your browser does not support Canvas.')
          }